server:
  port: 8080

targets:
  - path: "./access.log"
    table: "nginx_logs"
  - path: "./access_api.log"
    table: "api_logs"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

database:
  clear_on_startup: true
