server:
  port: 8080

auth:
  passport_url: "http://127.0.0.1:8089/api/v1/auth/check-token"

targets:
  - path: "./access.log"
    table: "nginx_logs"
  - path: "./access_api.log"
    table: "api_logs"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

database:
  clear_on_startup: true
